# Generated by Django 3.2.8 on 2021-11-10 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndes', models.TextField(max_length=1000)),
                ('ndate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spic', models.ImageField(default='', upload_to='static/slider/')),
                ('stitle', models.CharField(max_length=500)),
                ('sdes', models.TextField(max_length=2000)),
                ('sdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='videonews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlink', models.CharField(max_length=600)),
                ('vtitle', models.TextField(max_length=1000)),
                ('vnews', models.TextField(max_length=500)),
                ('vcity', models.CharField(max_length=100)),
                ('vdate', models.DateField()),
                ('vcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category')),
            ],
        ),
    ]
