# Generated by Django 3.2.8 on 2021-11-14 08:50

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20211112_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='ndes',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='videonews',
            name='vnews',
            field=tinymce.models.HTMLField(),
        ),
    ]
